version: 2
jobs:
  build:
    docker:
      - image:  microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: 
          command: dotnet restore
          working_directory: src
      - run: 
          command: dotnet pack --include-symbols --include-source -c Release /p:Version=0.1.0
          working_directory: src/GlobalX.AspNetCore.Hateoas.Siren
      - run:
          working_directory: src/GlobalX.AspNetCore.Hateoas.Siren
          command: echo 'dotnet nuget push -k $NUGET_KEY'  