version: 2
jobs:
  build:
    docker:
      - image:  microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: 
          command: dotnet restore
          working_directory: ~/src
      - run: 
          command: dotnet publish -C Release
          working_directory: ~/src
