version: 2
jobs:
  build:
    docker:
      - image:  microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: cd src
      - run: dotnet restore
      - run: dotnet publish -C Release
      - run: cd GlobalX.AspNetCore.Hateoas.Siren